[colors.primary]
background = "#0a1019"
foreground = "#c1c3c5"

[colors.cursor]
text = "#0a1019"
cursor = "#c1c3c5"

[colors.vi_mode_cursor]
text = "#0a1019"
cursor = "#c1c3c5"

[colors.search.matches]
foreground = "#0a1019"
background = "#c1c3c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#59616e"
background = "#c1c3c5"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0a1019"
red = "#877956"
green = "#3C8467"
yellow = "#4E8F6A"
blue = "#6EA06D"
magenta = "#93AD70"
cyan = "#B8CB76"
white = "#c1c3c5"

[colors.bright]
black = "#59616e"
red = "#877956"
green = "#3C8467"
yellow = "#4E8F6A"
blue = "#6EA06D"
magenta = "#93AD70"
cyan = "#B8CB76"
white = "#c1c3c5"

[colors.dim]
black = "#c1c3c5"
red = "#877956"
green = "#93AD70"
yellow = "#4E8F6A"
blue = "#6EA06D"
magenta = "#3C8467"
cyan = "#B8CB76"
white = "#59616e"

