[colors]
background = '#0a10198e'
black = '#0a1019'
blue = '#877956'
cursor = '#c1c3c5'
cyan = '#3C8467'
foreground = '#c1c3c5'
green = '#4E8F6A'
magenta = '#6EA06D'
red = '#93AD70'
tabs = '#c1c3c5'
tabs-active = '#B8CB76'
white = '#c1c3c5'
yellow = '#c1c3c5'
dim-black = '#0a10198e'
dim-blue = '#8779568e'
dim-cyan = '#3C84678e'
dim-foreground = '#c1c3c58e'
dim-green = '#4E8F6A8e'
dim-magenta = '#6EA06D8e'
dim-red = '#93AD708e'
dim-white = '#B8CB768e'
dim-yellow = '#c1c3c58e'
light-black = '#877956'
light-blue = '#3C8467'
light-cyan = '#4E8F6A'
light-foreground = '#6EA06D'
light-green = '#93AD70'
light-magenta = '#B8CB76'
light-red = '#c1c3c5'
light-white = '#877956'
light-yellow = '#3C8467'
