# Shell variables
# Generated by 'wal'
wallpaper="/home/bartek/hyprpaper.jpg"

# Special
background='#0a1919'
foreground='#c1c5c5'
cursor='#c1c5c5'

# Colors
color0='#0a1919'
color1='#1671C9'
color2='#5E97B6'
color3='#3388CE'
color4='#599ED1'
color5='#8EA4B8'
color6='#98B5CF'
color7='#c1c5c5'
color8='#596e6e'
color9='#1671C9'
color10='#5E97B6'
color11='#3388CE'
color12='#599ED1'
color13='#8EA4B8'
color14='#98B5CF'
color15='#c1c5c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
