[colors]
background = '#0a19198e'
black = '#0a1919'
blue = '#1671C9'
cursor = '#c1c5c5'
cyan = '#5E97B6'
foreground = '#c1c5c5'
green = '#3388CE'
magenta = '#599ED1'
red = '#8EA4B8'
tabs = '#c1c5c5'
tabs-active = '#98B5CF'
white = '#c1c5c5'
yellow = '#c1c5c5'
dim-black = '#0a19198e'
dim-blue = '#1671C98e'
dim-cyan = '#5E97B68e'
dim-foreground = '#c1c5c58e'
dim-green = '#3388CE8e'
dim-magenta = '#599ED18e'
dim-red = '#8EA4B88e'
dim-white = '#98B5CF8e'
dim-yellow = '#c1c5c58e'
light-black = '#1671C9'
light-blue = '#5E97B6'
light-cyan = '#3388CE'
light-foreground = '#599ED1'
light-green = '#8EA4B8'
light-magenta = '#98B5CF'
light-red = '#c1c5c5'
light-white = '#1671C9'
light-yellow = '#5E97B6'
