--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bartek/hyprpaper.jpg"

-- Special
background="#0a1919"
foreground="#c1c5c5"
cursor="#c1c5c5"

-- Colors
color0="#0a1919"
color1="#1671C9"
color2="#5E97B6"
color3="#3388CE"
color4="#599ED1"
color5="#8EA4B8"
color6="#98B5CF"
color7="#c1c5c5"
color8="#596e6e"
color9="#1671C9"
color10="#5E97B6"
color11="#3388CE"
color12="#599ED1"
color13="#8EA4B8"
color14="#98B5CF"
color15="#c1c5c5"
