--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/etc/nixos/resources/hyprpaper.png"

-- Special
background="#0a1019"
foreground="#c1c3c5"
cursor="#c1c3c5"

-- Colors
color0="#0a1019"
color1="#877956"
color2="#3C8467"
color3="#4E8F6A"
color4="#6EA06D"
color5="#93AD70"
color6="#B8CB76"
color7="#c1c3c5"
color8="#59616e"
color9="#877956"
color10="#3C8467"
color11="#4E8F6A"
color12="#6EA06D"
color13="#93AD70"
color14="#B8CB76"
color15="#c1c3c5"
