foreground         #c1c3c5
background         #0a1019
background_opacity 1.0
cursor             #c1c3c5

active_tab_foreground     #0a1019
active_tab_background     #c1c3c5
inactive_tab_foreground   #c1c3c5
inactive_tab_background   #0a1019

active_border_color   #c1c3c5
inactive_border_color #0a1019
bell_border_color     #877956

color0       #0a1019
color8       #59616e
color1       #877956
color9       #877956
color2       #3C8467
color10      #3C8467
color3       #4E8F6A
color11      #4E8F6A
color4       #6EA06D
color12      #6EA06D
color5       #93AD70
color13      #93AD70
color6       #B8CB76
color14      #B8CB76
color7       #c1c3c5
color15      #c1c3c5
