# Shell variables
# Generated by 'wal'
wallpaper="/etc/nixos/resources/hyprpaper.png"

# Special
background='#0a1019'
foreground='#c1c3c5'
cursor='#c1c3c5'

# Colors
color0='#0a1019'
color1='#877956'
color2='#3C8467'
color3='#4E8F6A'
color4='#6EA06D'
color5='#93AD70'
color6='#B8CB76'
color7='#c1c3c5'
color8='#59616e'
color9='#877956'
color10='#3C8467'
color11='#4E8F6A'
color12='#6EA06D'
color13='#93AD70'
color14='#B8CB76'
color15='#c1c3c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
