# pywal theme for ghostty

background = 0a1019
foreground = c1c3c5
cursor-color = c1c3c5
selection-background = c1c3c5
selection-foreground = 0a1019

palette = 0=#0a1019
palette = 1=#877956
palette = 2=#3C8467
palette = 3=#4E8F6A
palette = 4=#6EA06D
palette = 5=#93AD70
palette = 6=#B8CB76
palette = 7=#c1c3c5
palette = 8=#59616e
palette = 9=#877956
palette = 10=#3C8467
palette = 11=#4E8F6A
palette = 12=#6EA06D
palette = 13=#93AD70
palette = 14=#B8CB76
palette = 15=#c1c3c5
