# pywal theme for ghostty

background = 0a1919
foreground = c1c5c5
cursor-color = c1c5c5
selection-background = c1c5c5
selection-foreground = 0a1919

palette = 0=#0a1919
palette = 1=#1671C9
palette = 2=#5E97B6
palette = 3=#3388CE
palette = 4=#599ED1
palette = 5=#8EA4B8
palette = 6=#98B5CF
palette = 7=#c1c5c5
palette = 8=#596e6e
palette = 9=#1671C9
palette = 10=#5E97B6
palette = 11=#3388CE
palette = 12=#599ED1
palette = 13=#8EA4B8
palette = 14=#98B5CF
palette = 15=#c1c5c5
