include ~/.config/kitty/mocha.conf
font_family      family="JetBrainsMonoNL Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
cursor_style beam
enable_graphics yes
window_padding_width 5 10
confirm_os_window_close 0
background_opacity 0.5
background_blur 64
hide_window_decorations yes
tab_bar_style hidden
